### ISSUE TITLE
Dragster is unlicensed, prohibiting users from reproducing it, distributing it, or creating derivative works

### ISSUE THREAD

**Issue by openjck** [bensmithett/dragster#15]
Dragster is unlicensed. I'm not a lawyer, but this appears to prohibit others from distributing this code or creating derivative works. I assume this is unintentional.

From the [GitHub guidance on licensing](https://help.github.com/en/articles/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by bensmithett** [comment]
@openjck it doesn't have a `LICENSE.md` per github norms, but it's MIT: https://github.com/bensmithett/dragster#license

Reproduce! Distribute! Derive!

I've got a list of things to do to this repo when I get a spare few hours since I just realised people are still using it (🔥 coffeescript, add to npm), I'll add a `LICENSE.md` to the list. Or feel free to PR!

**Comment by openjck** [comment]
Ah, I'm sorry I missed that. I'll open a PR to add a LICENSE file.
